### ISSUE TITLE
Integrate with Travis-CI

### ISSUE THREAD

**Issue by zephraph** [zephraph/atom-robotframework#4]
Atom has a CI setup already. 

Just need to add the following into a ```.travis.yml``` file

```yml
language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10
```
